name: CI
on:
  push:
    branches:
      - master
    paths:
      - 'CMakeLists.txt'
      - 'src/**'
      - 'include/**'
      - '.github/scripts/*'
      - '.github/workflows/ci.yml'
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-w64-mingw32-cxx11
          - x86_64-apple-darwin14-cxx11
          - x86_64-linux-gnu-cxx11
          - x86_64-w64-mingw32-cxx11
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.3.1
      - name: Setup BinaryBuilder
        env:
          BINARYBUILDER_RUNNER: privileged
          BINARYBUILDER_AUTOMATIC_APPLE: true
        run: |
          julia --color=yes -e 'using Pkg; pkg"add BinaryBuilder; build"'
          julia --color=yes .github/scripts/build_tarballs.jl ${{ matrix.target }}
      - name: Publish
        if: startsWith(github.ref, 'refs/tags')
        run: julia --color=yes .github/scripts/build_tarballs.jl --deploy=rgcv/libcgal-julia_jll.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
